version: "3.8"
services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: oogiya/vim-flights-frontend:latest
    ports:
      - 3010:3000
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3011"
  backend-prod:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: oogiya/vim-flights-backend:latest
    ports:
      - 3011:3001
    environment:
      PORT: 3011
      NODE_ENV: production

  db:
    image: postgres
    volumes:
      - postgres_data:/home/node/app
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: flights
    ports:
      - 5432:5432

volumes:
  postgres_data:
